# Generated by Django 5.0.2 on 2024-02-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_rename_total_price_order_total_price_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
