version: '3.9'

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - test_app.wsgi:application
      - --bind
      - 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - database
    volumes:
      - static:/app/static

  database:
    image: postgres:14.10-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - DB_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - '5432:5432'

  nginx:
    image: nginx:1.24-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static:/static
    depends_on:
      - app

volumes:
  postgres_data:
  static:
